version: '3.1'
services:
  db:
    image: postgres:latest
    container_name: banco
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: hibernate
      POSTGRES_USER: hibernate
      POSTGRES_DB: hibernate